route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'telegram_alert_bot'

receivers:
  - name: 'telegram_alert_bot'
    telegram_configs:
      - bot_token_file: /config/bot-id.txt     
        api_url: https://api.telegram.org
        chat_id: -911387573
        parse_mode: 'HTML'
        message: '{{ template "telegram.html.message" . }}'

templates: 
  - "/config/templates/*.tmpl"
