services:

  prometheus:
    image: prom/prometheus:v2.54.1    
    container_name: prometheus
    ports: 
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - prometheus_data:/prometheus
    networks:
       my-network:
         ipv4_address: 172.75.0.2

  ssh-honeypot:
    image: ssh-test
    container_name: ssh-honeypot
    build: 
      context: ./honeypot
      dockerfile: Dockerfile
    ports: 
      - "22:22"
      - "8000:8000"
    volumes:
      - /var/log/kont:/var/log
    networks:
       my-network:
         ipv4_address: 172.75.0.4

  alertmanager:
    image: prom/alertmanager-linux-arm64:v0.27.0
    container_name: alertmanager
    ports: 
      - "9093:9093"
    volumes:
      - ./alertmanager:/config
    command:
      - "--config.file=/config/alertmanager.yml"
      - "--log.level=debug"
      - "--cluster.advertise-address=0.0.0.0:9093"
    networks:
      my-network:
        ipv4_address: 172.75.0.3


  grafana:
    image: grafana/grafana:11.2.0    
    container_name: grafana
    ports: 
      - "3000:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/main.yaml
    networks:
      my-network:
        ipv4_address: 172.75.0.5

volumes:
  prometheus_data:   

networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.75.0.0/16
