# Sample config for Prometheus.

global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['172.75.0.3:9093']

rule_files:
   - "alerting_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "ssh_honeypot"
    static_configs:
      - targets: ["172.75.0.4:8000"]
