{
 "title": "Honeypot Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Number of tested usernames and passwords",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "honeypot_usernames_tried_total", "legendFormat": "Usernames Tested" },
    { "expr": "honeypot_passwords_tried_total", "legendFormat": "Passwords Tested" }
   ]
  },
  {
   "title": "Alerts Firing List",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Percentage of successful and failed logins",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "honeypot_failed_logins_total" },
    {
     "expr": "honeypot_successful_logins_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of attempted and successful logins over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "honeypot_login_attempts_total", "legendFormat": "Login Attempts" },
    {
     "expr": "honeypot_successful_logins_total",
     "legendFormat": "Successful logins"
    }
   ]
  }
 ]
}